# Generated by Django 4.2.6 on 2023-10-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analise_Preco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='preco_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
