# Generated by Django 4.2.6 on 2023-10-11 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analise_Preco', '0002_alter_ativo_preco_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='tunel',
            field=models.CharField(choices=[('ESTATICO', 'Estático'), ('DINAMICO', 'Dinâmico Síncronos')], default='ESTATICO', max_length=8),
        ),
        migrations.AddField(
            model_name='ativo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Analise_Preco.usuario'),
        ),
    ]
