# Generated by Django 4.2.6 on 2023-10-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analise_Preco', '0003_usuario_ativo_tunel_ativo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='usuario',
        ),
    ]
