# Generated by Django 4.2.6 on 2023-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analise_Preco', '0005_ativo_spread_inferior_ativo_spread_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='spread_inferior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='spread_superior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
